config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'homes/about' => 'homes#about', as: 'about'
  resources :books, only: [:create, :edit, :index, :show, :destroy, :update]
  resources :users, only: [:edit, :index, :show, :destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update(book_params)
    redirect_to  book_path(book.id)
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @profile_image = @user.profile_image
  end

  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @books = Book.all
  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def index
    @user = current_user
    @users = User.all
    @books = @user.books
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    # @profile_image = @user.profile_image
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    @profile_image = @user.profile_image
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to users_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2 class="mt-3">New book</h2>
      <%= form_with model: book do |f| %>
        <div class="form-group">
          <%= f.label :title %><br>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Opinion</label><br>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Create Book", class:"btn btn-success" %>
        </div>
      <% end %>

app/views/books/edit.html.erb
<h2>Editing Book</h1>
<%= form_with model: @book do |f| %>
  <label for="inputTitle">Title</label>
  <%= f.text_field :title, autofocus: true, id: "inputTitle", placheholer: "Title" %>
  <label for="inputOption">Option</label>
  <%= f.text_area :body, autofocus: true, id: "inputOption", placheholer: "Option" %>
  <%= f.submit "Update Book" %>

  <%= link_to "Show", book_path(@book) %> |  <%= link_to "Back", books_path %>

<% end %>

app/views/books/index.html.erb
<p class="notice"><%= flash[:notice] %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list', user: @user %>
      <%= render 'books/list', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">Title</th>
            <th scope="col">Option</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= image_tag book.user.get_profile_image(100,100) %></td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list', user: @user %>
      <%= render 'books/list', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td><%= image_tag @user.get_profile_image(100,100) %><br>
            <%= link_to @user.name, user_path(@user.id) %></td>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
            <% if @user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success btn-sm" %></td>
              <td><%= link_to "destroy", book_path(@book), class:"btn btn-danger btn-sm", method: :delete %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1 class="px-3 mx-auto">Welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong> !!</h1>

      <p>In <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>

      <div class="col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block" %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/e709834f97.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="bg-dark text-white">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="h2">
            <%= link_to "Bookers", root_path %>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#NavbarDropdown" aria-controls="NavbarDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="NavbarDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id) do %>
                  <span class="fa-solid fa-house">Home</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path do %>
                  <span class="fa-solid fa-users">Users</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path do %>
                  <span class="fa-solid fa-book-open">Books</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <span class="fa-solid fa-right-from-bracket">Log out</span>
                <% end %>
              </li>
            <% else %>
            <li class="nav-item">
                <%= link_to root_path do %>
                  <span class="fa-solid fa-house">Home</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to about_path do %>
                  <span class="fa-solid fa-link">About</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path do %>
                  <span class="fa-solid fa-user-plus">Sign up</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path do %>
                  <span class="fa-solid fa-right-to-bracket">Log in</span>
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <p id=notice></p>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
<h2>User info</h2>
      <%= image_tag user.get_profile_image(100,100) %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></td>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
        <% if user == current_user %>
            <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
              <span class="fa-solid fa-user-gear"></span>
            <% end %>
          <% end %>
      </div>

app/views/users/edit.html.erb
<h2>User info</h1>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id: "inputName", placheholer: "名前" %>
  <label for="inputImage">Image</label>
  <%= f.file_field :profile_image, placheholer: "プロフィール画像", accept: "image/*" %>
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_area :introduction,autofocus: true, id: "inputIntroduction", placheholer: "紹介" %>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list', user: @user %>
      <%= render 'books/list', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">image</th>
            <th scope="col">name</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(100,100) %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list', user: @user %>
      <%= render 'books/list', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">Title</th>
            <th scope="col">Option</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= image_tag @user.get_profile_image(100,100) %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>